name: Test
on: [push, pull_request]
jobs:
  lint:
    name: pylint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: pylint
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
        pylint nari
